### ISSUE TITLE
bluebird: rename Promise class to BluebirdPromise

### ISSUE THREAD

**Issue by coot** [marudor/flowInterfaces#17]
Promise class is the ES6 Promise, it would be better to use a distinct class name for bluebird promise type.

**Comment by despairblue** [comment]
@marudor Having BluebirdPromise seems to be cleaner, but now we have to cast the BluebirdPromise into Promise whenever we use it with a method that declares that it uses `Promise`:

``` js
const bluebird = require('bluebird')

module.exports = function (obj: Object) : Promise<Object> {
  return Promise.resolve(bluebird.props(obj))
}
```

Is there a way to tell flow that a `BluebirdPromise` is a superset of a `Promise`?

**Comment by marudor** [comment]
@despairblue hmm indeed.

@coot
What's the preference here?

As I override the global Promise Object like this:

``` javascript
import BluebirdPromise from 'bluebird'
declare var Promise: BluebirdPromise
```

I do not really care.
But I tend to rename it back to Promise if it helps.
