### ISSUE TITLE
Bluebird type example

### ISSUE THREAD

**Issue by calebmer** [marudor/flowInterfaces#21]
First of all, thanks so much for these interfaces, they are truly amazing. But after using a bit of `iflow-bluebird`, I'm confused on how to type my promises.

I tried:

``` js
import Promise from 'bluebird'

const promise: Promise<string> = Promise.resolve('hello')

promise.then(hello => console.log(hello))
```

…which throws an error:

```
  6: const promise: Promise<string> = Promise.resolve('hello')
                    ^^^^^^^^^^^^^^^ type application of identifier `Promise`. Expected polymorphic type instead of
  6: const promise: Promise<string> = Promise.resolve('hello')
                    ^^^^^^^^^^^^^^^ class type: BluebirdPromise
```

So then I tried this:

``` js
import Promise from 'bluebird'

const promise: Promise = Promise.resolve('hello')

promise.then(hello => console.log(hello))
```

…which also didn't work. I believe this is because of [this](https://github.com/marudor/flowInterfaces/blob/master/packages/iflow-bluebird/index.js.flow#L134) line which wraps `BluebirdPromise` with `Class`, is it possible to remove the `Class` wrapper?

**Comment by marudor** [comment]
I'm usually doing this in a global libdef.

``` javascript
import BluebirdPromise from 'bluebird';
declare var Promise: BluebirdPromise;
```

Overwrites the global Promise with bluebird.

**Comment by calebmer** [comment]
Oh, so `import Promise from 'bluebird'` doesn't replace `Promise` locally?

**Comment by marudor** [comment]
Exactly.
Not sure but flow does it that way.

**Comment by calebmer** [comment]
Thanks!
