### ISSUE TITLE
iflow-lodash: _.create declaration appears to be wrong

### ISSUE THREAD

**Issue by benadamstyles** [marudor/flowInterfaces#52]
First off, I am no expert in inheritance, composition, OOP, not by a long way. However, I'm getting a persistent flow error using `_.create()` as follows:

``` js
type A = {
  a: number
}

type B = {
  getA: () => number
}

type Extended = A & B

const obj: A = {
  a: 5
}
const methods: B = {
  getA() {
    return this.a
  }
}

const final: Extended = _.create(methods, obj)
```

This is an attempted simplification of my case and the error I'm getting is the equivalent of:

```
call of method `create`. property `a`. Property not found in object type `methods`
```

The signature of `_.create` is:

```
create<T>(prototype: T, properties?: Object): $Supertype<T>
```

If I change this to the following, no errors are thrown:

```
create<T>(prototype: T, properties?: Object): $Subtype<T>
```

Again, I am no expert, but it makes sense to me that the return value of `_.create` is a subtype of `prototype`, not a supertype. Am I totally wrong?

**Comment by marudor** [comment]
lodash is now in flow-typed (https://github.com/flowtype/flow-typed)
