### ISSUE TITLE
Merge with flow-typed

### ISSUE THREAD

**Issue by marudor** [marudor/flowInterfaces#6]
Currently this repo is more quick & dirty to get started with libdefs.
https://github.com/splodingsocks/flow-typed had some discussion about structuring, testing, versioning and all that.
I think once they got started and are ready to be used we should merge.
Relevant Issue: https://github.com/splodingsocks/flow-typed/issues/4

**Comment by chrisbolin** [comment]
Oh, that'd be awesome!

**Comment by andreypopp** [comment]
What's the status of this?

**Comment by marudor** [comment]
@andreypopp All that are in here are not merged.
I've merged some. But it takes some time as I want them to be high quality for flow-typed.

Whenever I merge I deprecate the iflow- package though. So you will notice when you use one of the moved packages.

**Comment by bassettsj** [comment]
@marudor Could we move over the bluebird def, it doesn't look quite as difficult as some of the other ones. 😄

**Comment by marudor** [comment]
@bassettsj Currently I do not have the time. If you want you are free to merge them yourself.
I'm still watching the flow-typed repo. If something from here is there I am happy to deprecate it.

**Comment by turadg** [comment]
> If something from here is there I am happy to deprecate it.

These are in both now:
- bluebird
- debug
- deep-diff
- fuzzaldrin
- isomorphic-fetch
- lodash
- primus
- react-addons-test-utils
- react-redux

If the primary purpose of this repo is to have a place for libdefs that aren't up to flow-typed quality standards, what do you think of making each def into a PR in flow-typed? Then it would be clear where people should direct their efforts to improve them.

**Comment by marudor** [comment]
@turadg Thanks, I've deprecated the one in your list.

**Comment by steida** [comment]
Thank you very much for your work. Just a suggestion, react-intl should leverage https://flowtype.org/docs/objects.html#exact-object-types
