### ISSUE TITLE
Flow 0.33 keeps merging inference forever

### ISSUE THREAD

**Issue by jeroenbourgois** [marudor/flowInterfaces#65]
Hi! I added the lodash interface, but when running flow (version 0.33) it just keeps on saying `[merging inference]`. I know this can take some time, but after 2 hours on a 8core machine something is not right...

Do you have an idea how I could debug this?

**Comment by marudor** [comment]
Not relevant anymore as lodash is no in https://github.com/flowtype/flow-typed
