### ISSUE TITLE
react-router -> withRouter claim

### ISSUE THREAD

**Issue by 3runo** [marudor/flowInterfaces#68]
Hello, I believe it is a simple fix, I hope to have collaborated only with an image

![suggestion](https://cloud.githubusercontent.com/assets/5114769/19476436/f0fd3876-9517-11e6-87a9-c6ea0adb0730.jpg)

**Comment by Aldredcz** [comment]
Confirming, it's broken :(

**Comment by marudor** [comment]
Sorry, a bit tired when I merged the initial PR.
Fixed with db565e82295276628bc3db098327e3c81deebf8d
