### ISSUE TITLE
Some jQuery methods not chainable without causing incorrect Flow errors

### ISSUE THREAD

**Issue by joeldbirch** [marudor/flowInterfaces#78]
Incorrectly getting Flow error ”Property not found in String“ pertaining to any valid method that is chained after certain chainable jQuery methods, like `.attr()` and `.html()`.

The following is okay:

```js
/* @flow */

const myDiv: JQuery  = jQuery('#div')

myDiv
  .addClass('someclass')
  .attr('title', 'some title text')

// RESULT: no errors!
```
But chaining after `.attr()` shows errors:
```js
/* @flow */

const myDiv: JQuery  = jQuery('#div')

myDiv
  .addClass('someclass')
  .attr('title', 'some title text') // continue chaining…
  .removeClass('someotherclass')

// RESULT: “Flow: 1 error: property `removeClass` Property not found in String
```
The same occurs with `html()`:
```js
/* @flow */

const myDiv: JQuery  = jQuery('#div')

myDiv
  .addClass('someclass')
  .html('some html content') // continue chaining…
  .text('some content text')

// RESULT: “Flow: 1 error: property `text` Property not found in String
```

**Comment by Kocal** [comment]
See #74.

**Comment by joeldbirch** [comment]
I see, thanks for the info. So is that issue just awaiting a pull request with the reordered overloads?

**Comment by Kocal** [comment]
Yep. 

I'm actually editing `packages/iflow-jquery/index.js.flow` file (by changing overloads order for some methods) and I will make a pull request soon.

Actually, I can chain `.attr('foo', 'bar').addClass('baz')` (or the opposite), but it fails when `.text()` and `.html()` are not at the end of the chain:

```javascript
$el
.attr('foo', 'bar')
.addClass('baz')
.text('my text')
``` 

works, but 

```javascript
$el
.attr('foo', 'bar')
.text('my text')
.addClass('baz')
``` 

dont. 
I got the same error like you `property addClass. Property not found in String ($el)`.

I don't know what this error still happens. The definition ` text(text: string | number | boolean): JQuery` is the first of the three `text()` definitions (one with a Function parameter, the last one with no parameters).

You can always write `.text()` outside the chain, but you lost jQuery power...

I hope a "flow-interfaces-expert" will fix those bugs soon. 🤔
